services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - redis_data:/data

  api:
    build: .
    env_file:
      - .env
    ports:
      - 127.0.0.1:8080:8080
    restart: on-failure:5
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
